[features]
seeds = false
skip-lint = false
[programs.localnet]
yield_sol = "6D9vUu1jUuyYRTxZR5EMTM6sczptWWyK9Co6ty8gFL1x"

[programs.devnet]
yield_sol = "6D9vUu1jUuyYRTxZR5EMTM6sczptWWyK9Co6ty8gFL1x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/edujlac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
